### ISSUE TITLE
Pretty name in zurb_foundation_5.info

### ISSUE THREAD

**Issue by klonos** [backdrop-contrib/zurb_foundation_5#1]
The `name = zurb_foundation_5` line in `zurb_foundation_5.info` should be changed to `ZURB Foundation 5` (notice how the other themes have "pretty" names - proper casing and no underscores in them):

![backdrop-contrib_themes-zurb_foundation_5-pretty_name](https://cloud.githubusercontent.com/assets/2423362/9292097/b9f5f84a-4428-11e5-9da1-e29b7d3f2718.png)

**Comment by biolithic** [comment]
should be fixed in latest push, thanks for raising this issue
