### ISSUE TITLE
Messes with admin bar's style.

### ISSUE THREAD

**Issue by klonos** [backdrop-contrib/zurb_foundation_5#2]
Causes text to be bigger in admin bar + a big gap above it:

![backdrop-contrib_themes-zurb_foundation_5-messes_with_admin_bar_style](https://cloud.githubusercontent.com/assets/2423362/9292107/51cf16e2-4429-11e5-8c67-15e5b1f6eda9.png)

**Comment by biolithic** [comment]
should be fixed in latest push, thanks for raising this issue
